"""initial schema

Revision ID: 81211fc0af52
Revises: 
Create Date: 2026-02-13 18:41:38.283225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81211fc0af52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=500), nullable=True),
    sa.Column('default_model', sa.String(length=100), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('loan_product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('term_years', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('min_down_payment_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_credit_score', sa.Integer(), nullable=True),
    sa.Column('max_dti_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_loan_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility_requirements', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_product_is_active'), 'loan_product', ['is_active'], unique=False)
    op.create_index(op.f('ix_loan_product_type'), 'loan_product', ['type'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keycloak_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_keycloak_id'), 'user', ['keycloak_id'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_number', sa.String(length=20), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('loan_product_id', sa.UUID(), nullable=False),
    sa.Column('assigned_servicer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('personal_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('employment_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('financial_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('property_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('declarations', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('down_payment', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('dti_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_servicer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loan_product_id'], ['loan_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_application_applicant_status', 'application', ['applicant_id', 'status'], unique=False)
    op.create_index('idx_application_servicer_status', 'application', ['assigned_servicer_id', 'status'], unique=False)
    op.create_index(op.f('ix_application_applicant_id'), 'application', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_application_application_number'), 'application', ['application_number'], unique=True)
    op.create_index(op.f('ix_application_assigned_servicer_id'), 'application', ['assigned_servicer_id'], unique=False)
    op.create_index(op.f('ix_application_loan_product_id'), 'application', ['loan_product_id'], unique=False)
    op.create_index(op.f('ix_application_status'), 'application', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_resource', 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_application_type', 'document', ['application_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_document_application_id'), 'document', ['application_id'], unique=False)
    op.create_index(op.f('ix_document_document_type'), 'document', ['document_type'], unique=False)
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    op.create_table('info_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('requested_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_request_application_id'), 'info_request', ['application_id'], unique=False)
    op.create_index(op.f('ix_info_request_status'), 'info_request', ['status'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_unread', 'notification', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('risk_assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_band', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessment_application_id'), 'risk_assessment', ['application_id'], unique=False)
    op.create_index(op.f('ix_risk_assessment_status'), 'risk_assessment', ['status'], unique=False)
    op.create_table('decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('ai_recommendation', sa.String(length=50), nullable=True),
    sa.Column('servicer_agreed_with_ai', sa.Boolean(), nullable=True),
    sa.Column('override_justification', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('adverse_action_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('approved_loan_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('approved_term_years', sa.Integer(), nullable=True),
    sa.Column('monthly_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decision_date', 'decision', ['decided_at'], unique=False)
    op.create_index(op.f('ix_decision_application_id'), 'decision', ['application_id'], unique=True)
    op.create_index(op.f('ix_decision_decided_by'), 'decision', ['decided_by'], unique=False)
    op.create_index(op.f('ix_decision_decision'), 'decision', ['decision'], unique=False)
    op.create_table('risk_dimension_score',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=False),
    sa.Column('dimension_name', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('weighted_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('positive_factors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('mitigating_factors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('raw_agent_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_dimension_score_agent_name'), 'risk_dimension_score', ['agent_name'], unique=False)
    op.create_index(op.f('ix_risk_dimension_score_risk_assessment_id'), 'risk_dimension_score', ['risk_assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_dimension_score_risk_assessment_id'), table_name='risk_dimension_score')
    op.drop_index(op.f('ix_risk_dimension_score_agent_name'), table_name='risk_dimension_score')
    op.drop_table('risk_dimension_score')
    op.drop_index(op.f('ix_decision_decision'), table_name='decision')
    op.drop_index(op.f('ix_decision_decided_by'), table_name='decision')
    op.drop_index(op.f('ix_decision_application_id'), table_name='decision')
    op.drop_index('idx_decision_date', table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_risk_assessment_status'), table_name='risk_assessment')
    op.drop_index(op.f('ix_risk_assessment_application_id'), table_name='risk_assessment')
    op.drop_table('risk_assessment')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index('idx_notification_unread', table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_info_request_status'), table_name='info_request')
    op.drop_index(op.f('ix_info_request_application_id'), table_name='info_request')
    op.drop_table('info_request')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_index(op.f('ix_document_document_type'), table_name='document')
    op.drop_index(op.f('ix_document_application_id'), table_name='document')
    op.drop_index('idx_document_application_type', table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('idx_audit_log_resource', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_application_status'), table_name='application')
    op.drop_index(op.f('ix_application_loan_product_id'), table_name='application')
    op.drop_index(op.f('ix_application_assigned_servicer_id'), table_name='application')
    op.drop_index(op.f('ix_application_application_number'), table_name='application')
    op.drop_index(op.f('ix_application_applicant_id'), table_name='application')
    op.drop_index('idx_application_servicer_status', table_name='application')
    op.drop_index('idx_application_applicant_status', table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_keycloak_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_loan_product_type'), table_name='loan_product')
    op.drop_index(op.f('ix_loan_product_is_active'), table_name='loan_product')
    op.drop_table('loan_product')
    op.drop_table('llm_config')
    # ### end Alembic commands ###
